version: "3.9"

services:
  data-generator:
    build: .
    container_name: data-generator
    restart: "no"

    environment:
      - SIZE=S
      - SEED=42
      - SNAPSHOT_DATE=2026-02-01

    volumes:
      - ./output:/app/output
